### ISSUE TITLE
Error when plan or test does not exist in queried repository

### ISSUE THREAD

**Issue by janhavlin** [teemtee/web#11]
When a queried plan or test does not exist in a repository that is being queried, the app tracebacks. I used this url: http://localhost:8000/?plan-url=https://gitlab.com/testing-farm/gluetool-modules&plan-name=/testing-farm/sanity

```
[celery] | [2024-10-25 11:36:46,471: ERROR/ForkPoolWorker-16] Task tmt_web.service.main[b3690954-f50b-477f-9578-5f193e9a9571] raised unexpected: IndexError('list index out of range')
[celery] | Traceback (most recent call last):
[celery] |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
[celery] |     R = retval = fun(*args, **kwargs)
[celery] |                  ^^^^^^^^^^^^^^^^^^^^
[celery] |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
[celery] |     return self.run(*args, **kwargs)
[celery] |            ^^^^^^^^^^^^^^^^^^^^^^^^^
[celery] |   File "/app/tmt_web/service.py", line 186, in main
[celery] |     return process_plan_request(plan_url, plan_name, plan_ref, plan_path, True, out_format)  # type: ignore [arg-type]
[celery] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[celery] |   File "/app/tmt_web/service.py", line 112, in process_plan_request
[celery] |     wanted_plan = tree.plans(names=[plan_name])[0]
[celery] |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
[celery] | IndexError: list index out of range
```

Same logic applies when querying for a test:
```
[celery] | [2024-10-25 11:39:46,178: ERROR/ForkPoolWorker-16] Task tmt_web.service.main[f89e8cf7-4f0e-4872-b1ac-854151ee8515] raised unexpected: IndexError('list index out of range')
[celery] | Traceback (most recent call last):
[celery] |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
[celery] |     R = retval = fun(*args, **kwargs)
[celery] |                  ^^^^^^^^^^^^^^^^^^^^
[celery] |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
[celery] |     return self.run(*args, **kwargs)
[celery] |            ^^^^^^^^^^^^^^^^^^^^^^^^^
[celery] |   File "/app/tmt_web/service.py", line 184, in main
[celery] |     return process_test_request(test_url, test_name, test_ref, test_path, True, out_format)  # type: ignore [arg-type]
[celery] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[celery] |   File "/app/tmt_web/service.py", line 71, in process_test_request
[celery] |     wanted_test = tree.tests(names=[test_name])[0]
[celery] |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
[celery] | IndexError: list index out of range
```

**Comment by martinhoyer** [comment]
Hey @janhavlin, do you know if this still needs to be addressed?

**Comment by janhavlin** [comment]
Yes, the result now looks sane for me for both html and json outputs: http://tmt.staging.testing-farm.io/?plan-url=https://gitlab.com/testing-farm/gluetool-modules&plan-name=/testing-farm/sanity

Closing.
